{
 "title": "Vancouver Property Tax Prediction Model Dashboard",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Column Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Median Prediction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", median_prediction FROM metrics LIMIT 50 "
    }
   ]
  }
 ]
}